

document.write("<link rel="stylesheet" href="https://epaportal.sp.ohio.gov/DERR/DERR Site Assets/Style/SABRcustomModal.css">");
document.write("<link rel="stylesheet" href="http://oepa2016.github.io/codes/SABRdialog.css">");

document.write("<script type="text/javascript" src="/DERR/DERR%20Site%20Assets/Style/SABRdialogPopUp.js" language="JavaScript"></script>");
document.write("<script src="https://code.jquery.com/jquery-1.11.1.js"></script>");
document.write("<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>");
document.write("<script type="text/javascript" src="/DERR/DERR%20Site%20Assets/Style/jQueryAccordionTabs.js" language="JavaScript"></script>");

document.write("<!--[if lt IE 9]><script>window.ltIE9=true</script><![endif]-->");


document.write('<div id="sectionName">');
document.write('Site Assistance and Brownfield Revitalization');
document.write('</div>');
document.write('<ul class="top-level-menu">');
document.write('<li>');
document.write('<a href="#">');
document.write('Project Tracking');
document.write('</a>');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="#">');
document.write('CORF Projects');
document.write('</a>');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/CORF%20Project%20Status%20%28by%20City%29.pdf" target="_blank">');
							document.write('by City');
							document.write('</a>');
							document.write('</li>');
                  		 				 document.write('<li>');
							 document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/CORF%20Project%20Status%20%28by%20Project%29.pdf" target="_blank">');
							 document.write('by Project');
							 document.write('</a>');
							 document.write('</li>');
				document.write('<li>');
				document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/CORF%20Project%20Status%20%28by%20Round%29.pdf" target="_blank">');
				document.write('by Round');
				document.write('</a>');
				document.write('</li>');
document.write('<li>');
							 document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/Outstanding CORF Projects.pdf" target="_blank">');
							 document.write('Outstanding');
							 document.write('</a>');
							 document.write('</li>');
             		 	  document.write('</ul>');
           	 	document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('COAF Assess. Proj.');
document.write('</a>');
 document.write('<ul class="second-level-menu">');
                   		 	document.write('<li>');
							document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/COAF%20Assessment%20by%20City.pdf" target="_blank">');
							document.write('by City');
							document.write('</a>');
							document.write('</li>');
                  		 	 document.write('<li>');
							 document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/COAF%20Assessment%20by%20ProjectName.pdf" target="_blank">');
							 document.write('by Project');
							 document.write('</a>');
							 document.write('</li>');
             		 	  document.write('</ul>');
           	 	document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('COAF Cleanup Proj.');
document.write('</a>');
document.write('<ul class="second-level-menu">');
                   		 	document.write('<li>');
							document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/COAF%20Cleanup%20by%20City.pdf" target="_blank">');
							document.write('by City');
							document.write('</a>');
							document.write('</li>');
                  		 	 document.write('<li>');
							 document.write('<a href="http://epaintra.epa.ohio.gov/portals/4/documents/SABR-NET/docs/COAF%20Cleanup%20by%20ProjectName.pdf" target="_blank">');
							 document.write('by Project');
							 document.write('</a>');
							 document.write('</li>');
             		 	  document.write('</ul>');
           	 	document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/SiteAssets/current project summary.xlsx" target="_blank">');

document.write('TBAs');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Project%20Tracking/Audit_Outreach_Tracking_log.xls" target="_blank">');
document.write('CL Audit/Outreach');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Workgroups');
document.write('</a> ');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="#">');
document.write('Workgroup 1');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Workgroup 2');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Workgroup 3');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Quick Links');
document.write('</a> ');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="http://epaintra.epa.ohio.gov/Portals/4/Documents/docs/SIFU%20Tasking%20Form%20-%20final%20Aug%2019,%202014.docx" target="_blank">');
document.write('SIFU Tasking');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Geophysical Tasking');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/RCRA/Lists/Risk Project Tracking/AllItems.aspx">');
document.write('CO Risk Support');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="http://epa.ohio.gov/portals/30/SABR/docs/TBA_Request_Letter_and_App.docx" target="_blank">');
document.write('TBA App.');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Projects');
document.write('</a> ');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a id="opener" href="JavaScript:;" target="_parent">');
document.write('Clean Ohio Projects');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Guidance/Policy');
document.write('</a>');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FGuidance%20and%20Policy%2FCOF%20VAP%20Guidance&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('COF/VAP Guidance');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FGuidance%20and%20Policy%2FTBA%20Guidance&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('TBA Guidance');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FGuidance%20and%20Policy%2FLab%20Guidance&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('Lab Guidance');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FGuidance%20and%20Policy%2FCP%20Guidance&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('CP Guidance');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FGuidance%20and%20Policy%2FEIP%20MOUs&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('EIP MOUs');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('<li>');
document.write('<a href="#">');
document.write('Forms/Templates');
document.write('</a> ');
document.write('<ul class="second-level-menu">');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FForms%20and%20Templates%2FVAP%20EIP%20Templates&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('VAP EIP Templates');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FForms%20and%20Templates%2FTBA%20Templates&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('TBA Templates');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FForms%20and%20Templates%2FLab%20Templates&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('Lab Templates');
document.write('</a>');
document.write('</li>');
document.write('<li>');
document.write('<a href="https://epaportal.sp.ohio.gov/DERR/SABR/Document%20Library/Forms/AllItems.aspx?RootFolder=%2FDERR%2FSABR%2FDocument%20Library%2FForms%20and%20Templates%2FCP%20Templates&FolderCTID=0x0120004E3C95E0EE0A4448BECF2D1C6DFFDA0A&View={A29FCFEE-A32D-46BA-891C-83DBF6E95628}" target="_parent">');
document.write('CP Templates');
document.write('</a>');
document.write('</li>');
document.write('</ul>');
document.write('</li>');
document.write('</ul>');

document.write('</div>');
